### ISSUE TITLE
关于“微端”网址

### ISSUE THREAD

**Issue by LanTingNormalPerson** [StareAbyss/FoodsVsMiceAutoAssistant#10]
faa目前对于微端的网址（my.4399.com/yxmsdzls/wd-air）可以正常使用，但有几个问题：
1，必须点进服务器才能正确运行faa
2，无法实现“完成后退出flash”的功能
3，没有将微端网址的使用写入说明文档中

**Comment by StareAbyss** [comment]
欢迎反馈

360X微端 有一个特性 其刷新游戏后如果已经完成登录和服务器选择, 会自动选择上一次服务器, 但相对应的, 如果是重新开启游戏, 服务器选择界面是没有上一次服务器界面的, 为了一致性, 需要用户自己手动输入服务器并完成选择.

这些特性导致了, 服务器必须由玩家自己完成选择, 并且退出flash无法实现

因此, 但这个问题并不会被修复, 但会增加后续文档更新
