### ISSUE TITLE
请求在签到流程中加入 月卡领取 每日签到下方四个宝箱领取

### ISSUE THREAD

**Issue by LanTingNormalPerson** [StareAbyss/FoodsVsMiceAutoAssistant#11]
可否在后续版本中，加入领取月卡（以及使用消耗品中使用月卡礼包），和每日签到页面的累计7/14/21/28天签到奖励的领取？

**Comment by StareAbyss** [comment]
欢迎反馈

关于这些问题
1. 可以加入领取月卡
2. 使用消耗品中的月卡礼包由于其外观和和大量贵重礼包相同, 故无法区分, 不考虑实现;
3. 可以考虑加入7/14/21/28天签到奖励的领取
