### ISSUE TITLE
关于跨服识图

### ISSUE THREAD

**Issue by LanTingNormalPerson** [StareAbyss/FoodsVsMiceAutoAssistant#13]
跨服识图这部分，可否适当改改，比如：
如果只有跨服截图1p，则1p创房2p进入
如果只有跨服截图2p，则2p创房1p进入
如果跨服截图1p和跨服截图2p都有，则先尝试1p创房2p进入，失败后尝试2p创房1p进入

提出这个问题是两方面考虑：
1，我把大号放在了2p的位置（因为绝大多数关卡都是2p创房，会有初始赠送的卡片，在悬赏、神殿等关卡会很有帮助，只需要自己修改一下config里的铲子位置即可），而跨服创房是由1p创建的，如果1p是小号，就会遇到未解锁或卡片不足以创房的问题
2，跨服有时候会遇到假房间bug，如果两个号都可以创房的话，或许能减轻这个bug的影响

**Comment by StareAbyss** [comment]
这个设计的目的 , 其实是针对好友添加的问题.
也就是 FAA的组队系统 设计初衷是希望玩家大号保留好友, 小号需要删除大量好友. 相对初始卡片其实是次要的.
而仅有跨服较高的难度, 和进入门票制度, 需要玩家用大号进行房间创立. 
考虑到该设计牵扯较大, 可能不会进行相关的更改.

虚假房间bug不会因为交换创房对象而减轻影响. 这个问题应当由游戏官方解决, 而非自动化测试.
