### ISSUE TITLE
关于公会副本

### ISSUE THREAD

**Issue by LanTingNormalPerson** [StareAbyss/FoodsVsMiceAutoAssistant#14]
公会副本建议也改成悬赏那样，可以玩家自行设置每个副本打0到3次

**Comment by StareAbyss** [comment]
感谢反馈

这个设计有不同的目的:
公会副本是每个副本有三次固定的掉落 因此完成3x3次即可. 若有特殊需求可以根据该关卡的编号直接进入.
悬赏副本则不是这样, 它根据方案和关卡难度, 可能需要完成多次以确保成功通关且积分足够而非限制掉落次数.
从简约设计的角度, 该建议不会被实装.
