### ISSUE TITLE
关于定时任务

### ISSUE THREAD

**Issue by LanTingNormalPerson** [StareAbyss/FoodsVsMiceAutoAssistant#19]
在全天双爆的时候，定时任务意义不大，只需要完成第一个任务序列后，继续完成第二个任务序列即可，这个可否整合进周六周日的特殊操作里？（周六周日即使勾选使用双爆卡，也不使用双爆卡）

更进一步的话，可以让玩家自行选择任务序列，是定时执行还是只需按顺序完成即可
也可以让玩家标记某些非周六周日的特殊日期为双爆日期，在这些日期中不执行定时任务序列，只需按顺序完成任务序列即可

**Comment by StareAbyss** [comment]
事实上目前的双暴卡功能, 会在周末自动跳过的, 这是已实现的功能
而玩家确实是可以自由选择任务序列的, 只要设置一个完整的配置,点击直接运行而非自动运行即可.
标记非周六周日为双暴日意义不大, 因为官方赠送的双暴卡数量是溢出的, 不需要省着用.

**Comment by LanTingNormalPerson** [comment]
> 感谢反馈! 事实上目前的双暴卡功能, 会在周末自动跳过的, 这是已实现的功能 而玩家确实是可以自由选择任务序列的, 只要设置一个完整的配置,点击直接运行而非自动运行即可. 标记非周六周日为双暴日意义不大, 因为官方赠送的双暴卡数量是溢出的, 不需要省着用. 对于你建议, 我需要更进一步的文字补充, 以让我理解你的想法.

比如我的配置无法用默认战斗方案挂sss评分的炼狱12，但我可以曲线救国，在第一个任务序列中，完成除跨服任务以外的所有公会任务，然后在第二个任务序列中，使用定制的战斗方案去挂公会任务的跨服任务。但我想要这样做，就只能使用定时任务（需要自己估算好所有任务所需的时间，并且留出足够的容错空间），而不是完成第一个任务序列后就立即执行下一个任务序列

**Comment by StareAbyss** [comment]
我是否可以理解为 一个todo列表里 的若干项任务 不是锁死的顺序, 而是 可以选择其中若干项任意排序(也可以重复出现任何项任务=).
这可能需要大规模重写代码. 短期内并没有这个计划.

**Comment by LanTingNormalPerson** [comment]
> 我是否可以理解为 一个todo列表里 的若干项任务 不是锁死的顺序, 而是 可以选择其中若干项任意排序(也可以重复出现任何项任务=). 这可能需要大规模重写代码. 短期内并没有这个计划.

假如我现在的任务序列1（常规日常流程）：
勇士副本双打8次
12次跨服
公会任务（包含跨服）（使用默认卡组和默认战斗方案）
公会副本
情侣任务
魔塔密室1P
双人魔塔

任务序列2（剩下可做的日常流程）
1P单人勇士副本2次
公会任务（包含跨服）（使用特定的卡组和专门制作的战斗方案）
魔塔密室2P

通过两个任务序列，即使1P和2P的勇士副本每日上限次数不同、公会跨服任务无法用默认卡组+默认战斗方案挂机，我仍然能够将它们全部完成

但，现在的faa要想完成我说的两个任务序列，只能估算时间然后设置好定时启动
比如我估计任务序列1需要6个小时，那我就需要填写1分钟后定时启动任务序列1+6.5个小时后定时启动任务序列2

而我想要的只是按顺序完成任务序列1和任务序列2即可（任务序列1完成后，自动继续任务序列2），这样可以不用估算任务序列1的耗时，也不用留出缓冲时间来保证任务序列1完成后才开始运行任务序列2
