### ISSUE TITLE
关于单人魔塔131~140层的自动承载卡

### ISSUE THREAD

**Issue by LanTingNormalPerson** [StareAbyss/FoodsVsMiceAutoAssistant#23]
云层的顺序是固定的，而魔塔的时间是有限的，再加上向上补云的存在，可以将131~139的自动承载卡适当调整：
131~134：只会在第3行（第1行云层）和第4行（第2行云层）有云洞，因此依靠向上补云机制，只需要在第4行第9列放承载卡即可
135：第5行（第3行云层）可以借助向上补云机制，在第6行第9列放承载卡处理，其余两行云层参考131~134层
136~139：只会在第6行（第3行云层）和第7行（第4行云层）有云洞，因此依靠向上补云机制，只需要在第7行第9列放承载卡即可
140：同理，依靠向上补云机制，只需要在第2行第9列和第7行第9列放承载卡即可（不使用向上补云机制，因为只能照顾到第2行云层，第一行云层仍然需要单独的一次放置来处理）

（其实就是稍微改改json文件就行了）

**Comment by StareAbyss** [comment]
感谢反馈, 会在1.3.1的修正版中, 更新该问题!
