### ISSUE TITLE
关于刷新游戏后长时间未进服务器导致软件闪退[1.3.0和1.3.1]

### ISSUE THREAD

**Issue by 3408495218** [StareAbyss/FoodsVsMiceAutoAssistant#25]
经过多次闪退观察，和查看日志，发现每次都是刷新网页后，选择服务器但没有进入，软件便一直卡在refresh game,直到闪退

**Comment by StareAbyss** [comment]
对于该问题, 极大概率已有固定的触发条件.
请检查, 是否为重新开启了游戏, 未选择区服, 便启动FAA, 因为在第一次启动游戏时, 游戏界面是没有最近游玩的服务器界面的, 需要玩家至少完成手动进入服务器一次后, 才能完成这一点.
如果是, 该问题为用户操作问题, 不需要解决.
如果否, 将记录该问题. 并尝试解决除错, 是否有更多有效信息帮助我定位该问题呢?

**Comment by 3408495218** [comment]
否，并非第一次启动游戏，刷新游戏后有上一次选择的服务器并位于第一位。初步推测为刷新后过快的点击选择服务器，但因个人设备反应速度不足的问题，导致没有正确进入游戏。是否可以添加类似超时重连的功能

**Comment by StareAbyss** [comment]
你所说的超时重连功能是存在的 且持续运作的.
我设置的最大容错时间 是10s, 如点击10s后刷新未能正常找到 "上一次选择的服务器" , 将会回到该步骤开始, 该步骤是一个循环体, 任何一步都有容错时间, 如果超时未找到对应元素则会回到循环体开头重新点击刷新按钮.
FAA中绝大部分操作, 均是先识图, 后点击, 而非简单的带有delay的点击序列, 不存在过快一说.

仍需要更多信息以供解决问题.
