### ISSUE TITLE
增加新功能提议

### ISSUE THREAD

**Issue by miao-jue** [StareAbyss/FoodsVsMiceAutoAssistant#258]
能否增添一个礼券购买魔塔通关次数的功能，以消耗多余的礼券

**Comment by StareAbyss** [comment]
1. 此类涉及到解除二级的功能需要大量的测试，且测试失败的后果可能极其严重。比如我本人早期损失了1wd，在开发二级相关高级功能时。
2. hlhy的bug我们难以预料，它的任何一个ui都可能失灵进而导致毁灭性的故障。
3. 这项开发收益极低，不如去多刷几次无限跨服。
综上，我们考虑过添加但最后否决了。
