### ISSUE TITLE
关于战斗方案

### ISSUE THREAD

**Issue by LanTingNormalPerson** [StareAbyss/FoodsVsMiceAutoAssistant#26]
战斗方案似乎是通过某种排序来确定位置的，但这样不利于玩家添加新的方案（如果新方案影响了玩家原有的战斗方案排序，则需要从影响的位置开始，全部重新调整一遍），有什么比较好的办法可以解决吗？比如通过战斗方案的名称来锁定战斗方案？

**Comment by StareAbyss** [comment]
欢迎反馈
之前群内有讨论过这个问题
实际上 就是依据操作系统的 标题文本默认排序 完成的排序 记录的也是索引
但问题是, faa不是联网的软件, 暂时无法通过给每个方案分配独立id来完成这件事情, 因此该问题的解决任重道远.
如有好的建议 欢迎继续讨论.

**Comment by LanTingNormalPerson** [comment]
> 欢迎反馈 之前群内有讨论过这个问题 实际上 就是依据操作系统的 标题文本默认排序 完成的排序 记录的也是索引 但问题是, faa不是联网的软件, 暂时无法通过给每个方案分配独立id来完成这件事情, 因此该问题的解决任重道远. 如有好的建议 欢迎继续讨论.

我截了一部分settings.json里的内容过来，来辅助表达我的意思：
    "current_plan": 1,
    "todo_plans": [
        {
            "name": "Default",
            "sign_in": {
                "active": true,
                "is_group": true
            },
            "fed_and_watered": {
                "active": true,
                "is_group": true
            },
            "use_double_card": {
                "active": false,
                "is_group": true,
                "max_times": 2
            },
            "warrior": {
                "active": false,
                "is_group": true,
                "max_times": 8,
                "deck": 1,
                "battle_plan_1p": 2,
                "battle_plan_2p": 3
这里的"battle_plan_1p":，或许可以识别战斗方案的名字（或者名字的unicode编码）而不是战斗方案的排序位置，比如默认战斗方案叫“1卡组-通用-1P.json”，那就检索它的名字“1卡组-通用-1P.json”或者unicode编码“1\u5361\u7ec4-\u901a\u7528-1P.json”，检索不到的话说明用户删掉或重命名了该方案，就显示“找不到战斗方案”或者显示空白就行
