### ISSUE TITLE
关于卡片放置策略

### ISSUE THREAD

**Issue by linjiayang2016** [StareAbyss/FoodsVsMiceAutoAssistant#27]
注意到，在巫毒12(CS-5-5)中，后排毁阵情况严重，需要将海星等主力卡放在前排。若依照此思路设计卡片布局，当四个需求木盘子的位置完成放置后，程序将继续尝试放置木盘子，而对已冷却好的海星视而不见，直到木盘子出现缺损，或间隔时间足够长。

经测试，若海星放在后排则情况有所缓解，除巫毒12(CS-5-5)外的关卡未经测试。

请问上述情况属于有意为之，还是卡片放置策略的缺陷？谢谢！

**Comment by StareAbyss** [comment]
这个问题 可能是因为部分电脑机型上和技能等级极高的木盘子相结合, 特殊的操作频率导致图像正好总是难以识别到木盘子进入CD的状态. 这个问题可能并不好修复. 但我已知晓,
感谢反馈!

**Comment by StareAbyss** [comment]
根据最新的测试, 这可能是由于 战斗方案执行器的bug 该bug可能已经修复.
