### ISSUE TITLE
签到等日常可能因加载速度过慢导致执行失败

### ISSUE THREAD

**Issue by mamaruo** [StareAbyss/FoodsVsMiceAutoAssistant#3]
以VIP签到为例，如视频所示，在加载完成之前按钮是灰色的，领取礼券的按钮也不会生效。若此时软件执行执行点击，签到失败。
今天（2-12）使用时出现了VIP签到有一个账号未生效的情况，猜测是这个原因导致的。编辑：2024-2-13再次出现。

https://github.com/StareAbyss/FoodsVsMouses_AutoAssistant/assets/37480168/0ba4ee9d-fe38-4b07-9757-d08b88b4d356

**Comment by StareAbyss** [comment]
已悉知，之后会考虑为此添加一个视图检测 将最长等待时间延长至10s

**Comment by StareAbyss** [comment]
已经在最新版本中添加了该问题的修正. 该问题应该会得到修复.
