### ISSUE TITLE
关于公会任务中的带卡任务问题

### ISSUE THREAD

**Issue by miao-jue** [StareAbyss/FoodsVsMiceAutoAssistant#31]
在执行公会任务中的携带卡片作战的任务时，进入关卡后，程序会一直优先点击需要放置的任务卡，而不优先放置产火卡，直到放下一张任务卡后才开始放置产火卡，这会导致带卡任务时常无法完成。
1.3.1和1.4.0版本中出现了此问题。
1.3.0版本中是先放产火卡，再放任务卡，并没有出现此问题。

**Comment by miao-jue** [comment]
以携带酒瓶炸弹的任务为例，放下人物后，一直点击酒瓶炸弹卡，不放置产火卡
[running_log.log](https://github.com/user-attachments/files/15881753/running_log.log)
![屏幕截图 2024-06-18 150201](https://github.com/StareAbyss/FoodsVsMiceAutoAssistant/assets/172879559/a08264f1-5cae-4a97-a113-f8624aabddbe)

**Comment by miao-jue** [comment]
以携带酒瓶炸弹的任务为例，放下人物后，一直点击酒瓶炸弹卡，不放置产火卡
[running_log.log](https://github.com/user-attachments/files/15881753/running_log.log)
![屏幕截图 2024-06-18 150201](https://github.com/StareAbyss/FoodsVsMiceAutoAssistant/assets/172879559/a08264f1-5cae-4a97-a113-f8624aabddbe)

**Comment by miao-jue** [comment]
以携带肥牛火锅的任务为例，放下人物后，一直点击肥牛火锅卡，不放置产火卡，直到放下一张肥牛火锅卡后，才放置产火卡
![image](https://github.com/StareAbyss/FoodsVsMiceAutoAssistant/assets/172879559/43ee6ada-fef0-46f0-9675-a1417e14fdba)
[Uploading running_log.log…]()

**Comment by StareAbyss** [comment]
感谢反馈.
捏,这个素特性呢 (大雾)
因为1.3.0的优先级放卡没有修好, 导致实际上仍然是火苗够放啥就放啥的状态.
而任务卡被设定为最高优先级, 进而导致了这个问题出现,解决方法只有带风化,只有任务卡在冷却状况下才会放置其它卡片.
因为该功能也被用于在部分大赛任务ban小火炉后, 使用酒精灯作为任务卡解决产火问题, 修改其优先级会导致二律背反. 
目前只能先进行观望等待进一步的方案.

**Comment by StareAbyss** [comment]
最近的更新中我尝试修复了这个问题, 将任务卡和承载卡优先级置于方案中第一张卡之后了. 该问题已经解决~
