### ISSUE TITLE
在battle_plan文件夹下删除已配置的战斗方案会导致FAA启动时报错

### ISSUE THREAD

**Issue by JerryZ233** [StareAbyss/FoodsVsMiceAutoAssistant#344]
## 版本
[v1.5.3 稳定版](https://github.com/StareAbyss/FoodsVsMiceAutoAssistant/releases/tag/v1.5.3)

## 问题描述
在任务列表中配置战斗方案后，在battle_plan文件夹下删除对应战斗方案会导致FAA再次启动时报错：

![image](https://github.com/user-attachments/assets/509063e8-23a2-43bc-a1d5-b0c0a30494e3)

解决方法是把有相同uuid的方案拖回去（如果方案uuid变过那拖回去也没用，例如1.5.3版本中设置A方案->战斗编辑器修改A方案并另存为B方案->不改变设置A方案的项目直接退出->删除A方案文件 就会触发这个bug，1.5.4目测是没这个问题），或者手动修改/删除settings.json，对没有编程经验的用户很不友好

建议做一个红字提示找不到对应方案，或者直接fallback到默认方案1

**Comment by StareAbyss** [comment]
了解 1.5.5版本正在着手修复相关问题ing
