### ISSUE TITLE
请求新增自动化练习卡牌熟练度功能

### ISSUE THREAD

**Issue by Cloud-Minor** [StareAbyss/FoodsVsMiceAutoAssistant#38]
在高级功能中能否新增一个练习卡牌熟练度的功能，主要流程为：
1. 创建并进入一个有初始火苗的房间，如：魔塔水晶宫/自定义关卡等；
2. 迅速下完需要练熟练度的卡牌
3. 退出战斗，回到第一步
4. （可选）根据期望技能等级和现有熟练度，计算需要执行的次数
5. （可选）使用（幻鸡/冰激凌/圣诞盒子）类卡牌
考虑到战斗部分与现有战斗流程开始是相似的，可能具体实现可以复用战斗流程。

**Comment by StareAbyss** [comment]
感谢建议
但在之前多次的交流中已经确立过了
FAA 完全不会考虑加入这类功能
原因是:
1. 有大量能很好完成该类功能的其他工具,
2. 和FAA的目标作用不一致, 过于臃肿.
