### ISSUE TITLE
关于触发二级密码的提议

### ISSUE THREAD

**Issue by 3408495218** [StareAbyss/FoodsVsMiceAutoAssistant#429]
版本1.5.7，通过卸下武器触发二级，可如果本身没有二级会导致武器被卸下。是否可以先判断二级不为空再卸下武器触发二级，若为空则跳过触发二级

**Comment by StareAbyss** [comment]
欢迎提交问题

不考虑该问题. 因为FAA明确注明了, 一定要有二级密码使用.
以防止游戏卡顿造成的不明原因错误, 进而导致账号损失.

这个密码可以特别简单 比如123456. 只要能防止出错就好.
这是对用户的虚拟财产安全的保障, 因此现在和未来均不会考虑不设二级.
