### ISSUE TITLE
跨服副本有概率失败

### ISSUE THREAD

**Issue by JerryZ233** [StareAbyss/FoodsVsMiceAutoAssistant#433]
## 版本
[v1.5.7](https://github.com/StareAbyss/FoodsVsMiceAutoAssistant/releases/tag/v1.5.7)

## 概述
双人进行跨服副本时，1p有概率创建房间失败，会导致1p和2p卡住或误进入别人的房间
经过观察，可能的原因是1p在创建房间时“右上角选择跨服x区”和“点击右下创建房间”中间的延迟时间过短，导致在网络延迟高的情况下后一操作失败。

## 修改建议
加长上述两操作之间的时间间隔，或者增加一些高级自定义功能允许用户自行调整各操作之间的时间间隔

**Comment by StareAbyss** [comment]
已修复
