### ISSUE TITLE
是否考虑一些新功能的点子？

### ISSUE THREAD

**Issue by Xiaye2332** [StareAbyss/FoodsVsMiceAutoAssistant#5]
目前使用版本是v1.0.0-beta-se
在使用下来后有几个地方觉得可以更新一步
1、增加一个使用定量双爆卡的日常，以方便后面的刷图（使用双爆卡不需要二级）
2、可以增加一个“自动开始”，每天定时自启刷图

另外，仓库的代码什么时候更新_(:з」∠)_）

**Comment by StareAbyss** [comment]
目前版本是v1.3.0
仓库的代码已更新
这两个功能已完成UI绘制，具体的实现之后有时间会做

**Comment by StareAbyss** [comment]
v1.3.1
已经完美实现上述两个功能！
