### ISSUE TITLE
可以增加一个对于勇士关卡的选择吗，

### ISSUE THREAD

**Issue by zhoumeng123456** [StareAbyss/FoodsVsMiceAutoAssistant#533]
因为全自动脚本打不过最后几张图，所以全开自动雪山图的时候，会出现棉花糖无法放置打不过的情况。希望能增加当前关卡和期望打的关卡的输入，根据输入选择点击几下前进键，然后根据期望打的关卡输入常规火山地图的对应参数，应该能解决火山勇士挑战不能正常放棉花糖的问题

**Comment by StareAbyss** [comment]
这个功能缺乏受众
1. 练度高了肯定只打最后一关
2. 练度低了刷三岛12卡练度高了随便打，攒好令牌，之后令牌是跟不上消耗的
故不考虑实现.

**Comment by StareAbyss** [comment]
啊！因为最近游戏的更新，该问题已经重新提上日程！并已经完成开发！
