### ISSUE TITLE
关于任务事项

### ISSUE THREAD

**Issue by LanTingNormalPerson** [StareAbyss/FoodsVsMiceAutoAssistant#9]
公会任务中有一些跨服任务，很难用默认卡组和默认战斗方案来一起完成（比如水火11、冰跨8和9等，尤其是水火这类地图涉及到双承载卡，需要玩家自己把岩浆的承载写进战斗方案里），可否把公会任务的跨服作为单独的一项，放到公会任务后面，这样更有助于一键实现全流程

**Comment by StareAbyss** [comment]
欢迎反馈

这其实存在2个问题
1. 公会跨服对应了大量不同的高难度的副本, 它们本身也很难被一个方案完成;
2. 水火副本是一个FAA长期不会进行支持的特例副本, 该副本价值极低且双承载对于FAA目前的架构难以实现需要涉及大量核心函数的重写;

考虑到这两点, 该问题暂不会进行处理.

**Comment by LanTingNormalPerson** [comment]
> 欢迎反馈
> 
> 这其实存在2个问题
> 
> 1. 公会跨服对应了大量不同的高难度的副本, 它们本身也很难被一个方案完成;
> 2. 水火副本是一个FAA长期不会进行支持的特例副本, 该副本价值极低且双承载对于FAA目前的架构难以实现需要涉及大量核心函数的重写;
> 
> 考虑到这两点, 该问题暂不会进行处理.

我的想法是，可否把跨服任务设计成一个任务组，因为任务只有10个，所以可以给每一个单独进行编辑，识别到哪个就执行哪个，这样也不用专门给水火副本进行双承载的函数重写了。并且，除了炼狱副本需要专门准备一个带棉花糖而不是麦芽糖的卡组（因为非常需要开局赠送的棉花糖），以及冰跨8和冰跨9需要带海盐粉，其他任务都是可以用默认卡组的，需要调整的只是战斗方案而已，只需要编辑这一次，以后就都可以无痛挂机了
